"use client"
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Toaster from "@/components/Toaster";
import TaskProvider from "@/context/productContext";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from './registry';
import {
  LayoutChildrenContainer
} from "./stylesLayout";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={inter.className}>
          <TaskProvider>
            <Header />
            <LayoutChildrenContainer >
              {children}
            </LayoutChildrenContainer>
            <Toaster position="bottom-left" />
            <Footer />
          </TaskProvider>
        </body>
      </StyledComponentsRegistry>
    </html>
  )
}