export const ENTITIES = {
  GENERAL:'general',
  CUSTOMERS: 'customers',
  CUSTOMER: 'customer',
  SUPPLIERS: 'suppliers',
  SUPPLIER: 'supplier',
  BRANDS: 'brands',
  BRAND: 'brand',
  PRODUCTS: 'products',
  PRODUCT: 'product',
  BUDGETS: 'budgets',
  BUDGET: 'budget',
  EVENTS: 'events',
  EXPENSES: "expenses",
  EXPENSE: "expense",
  USERS: 'users',
  USER: 'user',
  SETTINGS: "settings",
  CASH_BALANCES: "cash-balances",
  CASH_BALANCE: "cash-balance",
  CASHBALANCES:"cashBalances"
};